Traceback (most recent call last):
  File "main.py", line 182, in <module>
    print("Data preparation in progress for the {} dataset...".format(args.dataset))
AttributeError: 'Namespace' object has no attribute 'dataset'
